INSERT INTO steps (id, section_id, number, title, description)
VALUES
  -- Section 1: Caramelize Onions (Recipe 1: Shakshuka)
  (1, 1, 1, 'Slice Onions Thinly', 'Begin by selecting 4 large yellow onions - they should feel heavy for their size, indicating freshness and high moisture content. Peel away the papery outer layers and cut each onion in half from root to stem. Lay each half flat-side down on your cutting board for stability, which is crucial for safety and uniform slices. Using a sharp chef''s knife, slice each half into thin half-moons, approximately 1/8 to 1/4 inch thick. The key here is consistency - uniformly thin slices will caramelize evenly, while thicker pieces will still be raw when the thinner ones start to burn. Don''t worry if your eyes water; this is a normal reaction to the sulfur compounds released when cutting onions. Some cooks keep their onions refrigerated before cutting to minimize tears. Once sliced, you should have about 8 cups of raw onions, which will reduce dramatically during cooking. Keep the slices together and have them ready before you start cooking, as once the process begins, you''ll need to stay attentive.'),
  (2, 1, 2, 'Cook Low and Slow', 'Heat a large, heavy-bottomed pot or Dutch oven over medium heat and add 3-4 tablespoons of unsalted butter. The heavy bottom is important as it distributes heat evenly and prevents hot spots that could cause burning. Once the butter has completely melted and begins to foam, add all your sliced onions at once. They will pile high in the pot initially, but don''t worry - they''ll reduce to about one-sixth of their original volume. Stir the onions to coat them evenly with butter, then reduce the heat to medium-low. This is where patience becomes your greatest virtue. The onions need to cook slowly, allowing their natural sugars to caramelize without burning. For the first 15-20 minutes, stir every 5 minutes or so. You''ll notice the onions beginning to soften and release their moisture. As they continue cooking, they''ll start to turn translucent, then golden, and finally that beautiful deep mahogany brown. During the last 20-30 minutes, you''ll need to stir more frequently, perhaps every 3-5 minutes, as the natural sugars concentrate and the risk of burning increases. If you notice any bits sticking to the bottom of the pot, don''t panic - this is actually flavor developing. Just scrape them up with your spoon and incorporate them back into the onions. The entire process typically takes 45-60 minutes, sometimes even longer. You''ll know they''re done when they''re deeply colored, very soft, and have a sweet, rich aroma. The volume will have reduced dramatically, and you''ll be left with about 1-1.5 cups of concentrated onion gold.'),
  (3, 1, 3, 'Add Sugar and Wine', 'Once your onions have reached that perfect deep caramel color, it''s time to add the final flavor-boosting elements. Sprinkle 1 teaspoon of granulated sugar evenly over the onions and stir to incorporate. This small amount of added sugar helps accelerate the final stages of caramelization and deepens the color even further. Cook for another 2-3 minutes, stirring constantly, until the sugar melts and mingles with the onions. Now comes one of the most satisfying steps in cooking - deglazing. Pour in 1/4 cup of dry white wine (a Chardonnay or Sauvignon Blanc works well) and immediately use a wooden spoon to scrape up all those caramelized bits stuck to the bottom of the pot. These browned bits, called fond in culinary terms, are concentrated flavor bombs that you absolutely want to incorporate into your soup. As the wine sizzles and steams, it will loosen these bits and dissolve them into the liquid. Continue stirring for 2-3 minutes until most of the wine has evaporated and reduced, leaving behind its flavor but not too much liquid. The onions should now be glossy, deeply colored, and incredibly aromatic. This is the flavor foundation that will make your French onion soup legendary. At this point, you could even make extra caramelized onions and freeze them in portions for future use - they''re that versatile and delicious.'),

  -- Section 2: Build the Soup (Recipe 1: Shakshuka)
  (4, 2, 1, 'Add Broth', 'Now that your onions are perfectly caramelized and deglazed, it''s time to transform them into soup. Slowly pour in 8 cups of high-quality beef broth, stirring as you add it to incorporate the caramelized onions throughout. The quality of your broth is paramount here - if you have the time and inclination, homemade beef stock will elevate this soup from excellent to extraordinary. Look for a broth that''s rich and flavorful, preferably one with a good amount of gelatin (it should be slightly jiggly when cold). If using store-bought, choose a low-sodium variety so you can control the salt level yourself. As you add the broth, you''ll see the deep brown color from the onions dispersing throughout the liquid, creating that signature French onion soup hue. Use your wooden spoon to scrape any remaining fond from the bottom and sides of the pot - every bit adds flavor. Gradually increase the heat to medium-high and bring the soup to a gentle simmer. You''ll see small bubbles breaking the surface regularly, but it shouldn''t be at a rolling boil. This gentle simmer is important for developing flavors without reducing the broth too quickly or making it cloudy.'),
  (5, 2, 2, 'Season', 'Seasoning is where you can make this soup truly your own while respecting the classic French tradition. Add 3-4 sprigs of fresh thyme - the woody herb''s earthy notes complement the sweetness of the caramelized onions beautifully. If you can only find dried thyme, use about 1 teaspoon, though fresh is definitely preferable. Drop in 2 bay leaves, which will add a subtle, complex background note. Some traditional recipes also add a splash of cognac or brandy at this stage for depth, though this is optional. Now taste your soup - this is crucial. Add salt gradually, stirring and tasting between additions. Remember that the broth already contains some sodium, and you''ll be adding salty cheese later, so err on the side of underseasoning at this stage. Freshly ground black pepper should be added generously - about 1/2 teaspoon to start, or more if you like a peppery kick. Some cooks also add a pinch of sugar to balance any acidity from the wine, though with properly caramelized onions, this usually isn''t necessary. The soup should taste rich, savory, and balanced at this stage.'),
  (6, 2, 3, 'Simmer', 'Reduce the heat to low and let the soup simmer gently, uncovered, for at least 30 minutes. During this time, the flavors will meld and deepen in complexity. The herbs will infuse their aromatic oils into the broth, the onions will soften even further and distribute their caramelized flavor throughout, and the liquid will reduce slightly, concentrating the taste. Some traditional French recipes simmer for up to an hour for maximum flavor development. As it simmers, you''ll notice the aroma filling your kitchen - that rich, savory, slightly sweet smell is irresistible. Skim off any foam or impurities that rise to the surface, though there shouldn''t be much if you''re using quality broth. Give it an occasional stir to prevent the onions from settling and potentially sticking to the bottom. After 30 minutes, taste again and adjust seasoning as needed. The soup should be deeply flavored, with the sweetness of the onions balanced by the savory broth and aromatics. At this point, you can remove and discard the bay leaves and thyme sprigs (or leave them in for a more rustic presentation). The soup can be made ahead to this point and refrigerated for up to 3 days, or frozen for up to 3 months - many claim it tastes even better the next day as the flavors continue to develop.'),

  -- Section 3: Gratinée and Serve (Recipe 1: Shakshuka)
  (7, 3, 1, 'Toast Bread', 'The bread component is crucial to authentic French onion soup gratinée, serving both structural and flavor purposes while providing textural contrast to the silky soup below. Select a high-quality French baguette - it should have a crispy crust and a tender, airy interior with good structure. Day-old bread actually works better than fresh for this application, as it''s slightly drier and won''t get as soggy when sitting in the hot soup. Using a serrated knife, slice the baguette on a diagonal into rounds approximately 3/4 to 1 inch thick - these diagonal slices will be larger and provide better coverage for your soup crocks. Arrange the slices in a single layer on a baking sheet. You can brush them lightly with olive oil if desired, though this isn''t strictly necessary. Place the baking sheet in a preheated 375°F oven or under the broiler and toast the bread slices until they''re completely dry and golden brown on both sides, flipping once halfway through. This usually takes about 8-10 minutes in the oven, or 2-3 minutes per side under the broiler - watch carefully if broiling as bread can go from golden to burnt very quickly. The bread should be crispy throughout, not just on the surface. When you tap it, it should sound hollow and feel hard rather than having any give. This thorough toasting is essential - it creates a moisture barrier that prevents the bread from immediately dissolving into the soup, allowing it to maintain some texture even after absorbing liquid. Some traditional recipes even toast the bread twice to ensure maximum crispness. You can prepare these toasts ahead of time and store them in an airtight container for a day or two.'),
  (8, 3, 2, 'Assemble', 'The assembly process requires organization and speed, as you want everything to come together while still hot so the cheese can properly melt and create that characteristic stretchy, golden topping. Select individual oven-safe crocks or bowls - traditional French onion soup crocks are ceramic with handles, typically holding about 12-16 ounces, but any oven-safe bowls will work. Arrange your empty crocks on a sturdy baking sheet for easy handling - this also catches any drips or overflow during the broiling process. Ladle the hot soup into each crock, filling them to within about an inch of the rim. You need to leave space for the bread and cheese without overflow. The soup should be steaming hot - if it has cooled, reheat it gently before assembling. Place one or two pieces of your toasted bread on top of each crock, pressing down slightly so they''re partially submerged but still floating on the surface. The bread should mostly cover the soup but doesn''t need to create a perfect seal - some soup showing around the edges is fine and actually looks more rustic and authentic. Now comes the cheese - use freshly grated Gruyère for the best melting and flavor. Pre-grated cheese contains anti-caking agents that prevent proper melting and create a grainy texture rather than the smooth, stretchy result you want. Pile the grated cheese generously over the bread, completely covering it and extending over the edges to the rim of the crock. Don''t be shy with the cheese - you want a thick layer that will melt down and create a substantial topping. The cheese hanging over the edges will melt down the sides of the crock and caramelize, creating those delicious crispy bits. Some cooks like to mix a small amount of grated Parmesan with the Gruyère for extra flavor and browning.'),
  (9, 3, 3, 'Broil', 'The final broiling step is where the magic happens, transforming individual components into the unified, glorious dish that French onion soup is famous for, with that irresistible combination of melted, browned cheese and rich, oniony soup beneath. Position your oven rack in the upper third of the oven, typically about 6 inches from the heating element - close enough for effective browning but not so close that the cheese burns before it melts. Preheat your broiler to high. Carefully transfer your baking sheet with the assembled soup crocks to the oven. If your crocks have handles, make sure they''re facing outward for easy removal. Close the oven door and watch carefully - broiling happens fast and can go from perfectly golden to burnt in seconds. The cheese will begin to melt first, bubbling and spreading to cover any gaps. As it continues heating, it will start to brown, first turning light golden and then developing those darker, caramelized spots that provide concentrated flavor. This typically takes 3-5 minutes, but timing varies widely depending on your broiler''s power and the distance from the element. You want the cheese to be melted throughout, bubbling vigorously, and deeply golden brown on top with some darker spots - these are not burns but delicious caramelization. The cheese should have that characteristic pulled-sugar appearance when you break through it with a spoon. The soup underneath should be bubbling hot - you should hear it sizzling under the cheese blanket. When it looks perfect, remove the baking sheet from the oven using oven mitts - remember, the crocks and sheet are extremely hot. Let the soup rest for about a minute to allow the bubbling to calm down and prevent burns when eating. Serve each crock on a trivet or heat-resistant plate with a warning that it''s extremely hot. The proper way to eat it is to break through that cheese crust with your spoon, pulling up strings of melted cheese along with bread-thickened soup. It''s rich, satisfying, and utterly delicious - the perfect marriage of sweet caramelized onions, savory broth, and funky, melted cheese.'),

  -- Section 4: Make Dressing (Recipe 2: Grandma's Secret Meatballs - PRIVATE)
  (10, 4, 1, 'Combine Base', 'The foundation of Caesar dressing is an emulsion of egg yolks with flavor-packed ingredients, and getting this base right is essential for a dressing that''s creamy, stable, and bursting with umami richness. Start with room temperature egg yolks - cold yolks don''t emulsify as readily and can lead to a broken, separated dressing. Crack your eggs carefully, separating the yolks from the whites with precision. Save the whites for another use, like meringues or an egg white omelet. Place the two yolks in a medium bowl. Now for the anchovies - don''t even think about skipping them or the dressing will lack that essential savory depth. Use good quality anchovies packed in olive oil, preferably Italian or Spanish. Drain them and pat dry with paper towels. You need about 4-6 fillets depending on their size and your taste preferences. Mince them into a fine paste using a sharp knife, then use the flat of your knife to smear and mash them against the cutting board until they form a smooth paste. This breaks down the fish completely so you won''t have chunks in your dressing. Add the anchovy paste to the egg yolks. Next comes the garlic - fresh is absolutely mandatory here. Peel 2-3 cloves and mince them very finely, then sprinkle with a pinch of salt and use the flat of your knife to smear and mash them into a paste, just like you did with the anchovies. The salt acts as an abrasive and helps break down the garlic''s cell walls, releasing its oils and creating a smooth paste rather than bits of sharp raw garlic. Add the garlic paste to the bowl with the yolks and anchovies. Using a whisk, beat everything together vigorously for about 30 seconds until the mixture is completely smooth and homogeneous, with no visible pieces of anchovy or garlic remaining. The mixture should be thick, pasty, and deeply flavored already - this is your flavor base that will be diluted and enriched by the oil you''ll add later.'),
  (11, 4, 2, 'Add Acid', 'The acidic components in Caesar dressing serve multiple crucial functions - they provide brightness that cuts through the richness of the egg yolks and oil, they help stabilize the emulsion, and they add their own layers of flavor complexity that round out the dressing beautifully. Squeeze fresh lemon juice - you''ll need about 2 tablespoons, which typically comes from one large lemon. Roll the lemon firmly on your counter before cutting to break down the membranes and release more juice. Cut it in half and juice it, straining out any seeds. Fresh lemon juice is infinitely superior to bottled - the bright, vibrant acidity and the subtle floral notes of fresh juice can''t be replicated by the flat, one-dimensional taste of bottled lemon juice. Add the lemon juice to your egg yolk mixture. Next comes Dijon mustard, which might not be traditional in the oldest Caesar recipes but has become standard in modern versions and contributes both flavor and emulsifying power. The mustard contains natural emulsifiers that help stabilize the dressing and prevent it from breaking or separating. Use about 1-2 teaspoons of good quality Dijon - look for one that lists mustard seeds, vinegar, and salt as the main ingredients without a lot of additives. Add it to the bowl. Using your whisk, beat everything together vigorously until completely combined and slightly frothy. The mixture will loosen up considerably with the addition of these liquids, going from thick and pasty to more pourable. The color will lighten to a pale yellow, and you should be able to smell the sharp acidity of the lemon and mustard along with the pungent garlic and savory anchovies. Taste a tiny bit on your finger - it should be intensely flavored, almost too much so, because it''s about to be diluted significantly by the oil. The balance should be salty, savory, acidic, and pungent all at once.'),
  (12, 4, 3, 'Emulsify Oil', 'The emulsification process is where kitchen chemistry creates magic, transforming separate ingredients into a smooth, creamy, stable dressing through the power of constant agitation and slow incorporation, and mastering this technique will serve you well in countless other recipes from mayonnaise to vinaigrettes. Have your olive oil measured and ready in a container with a spout for easy pouring - you''ll need about 3/4 cup, possibly more depending on how thick you like your dressing. Extra virgin olive oil will give you the most flavor, though some people find it too peppery and prefer a milder regular olive oil or even a blend of olive oil with a neutral oil like grapeseed. Begin whisking your egg yolk mixture vigorously, creating a whirlpool in the center of the bowl. While continuing to whisk without stopping, start adding the oil literally one drop at a time. This is not an exaggeration - in the beginning, adding too much oil at once will cause the emulsion to break before it even forms. After you''ve added about a tablespoon of oil this way, whisking constantly, the mixture will begin to thicken and lighten in color. This is the emulsion forming - tiny droplets of oil being suspended in the egg yolk mixture, coated by the emulsifiers in the egg and mustard. Once you see this thickening happening, you can begin adding the oil in a very thin, steady stream rather than drops, but still whisking vigorously and continuously. Never stop whisking during this process. As you add more oil, the dressing will continue to thicken, becoming pale, creamy, and voluminous. If at any point it becomes so thick that it''s difficult to whisk, add a few drops of water or lemon juice to thin it slightly. Keep adding oil and whisking until you''ve incorporated all of it and the dressing has reached your desired consistency - it should be thick enough to coat the back of a spoon, creamy and smooth with no separation, and pale yellow in color. If your dressing breaks or separates at any point - meaning the oil pools separately from the other ingredients - don''t panic. Start with a fresh egg yolk in a clean bowl and slowly whisk the broken dressing into it as if it were oil, and it should come back together.'),

  -- Section 5: Prepare Croutons (Recipe 2: Grandma's Secret Meatballs - PRIVATE)
  (13, 5, 1, 'Cut Bread', 'The bread selection and cutting technique are more important than you might think when it comes to making perfect croutons that are crispy throughout while maintaining structural integrity and providing that satisfying crunch in every bite of your Caesar salad. Start with a good quality rustic bread - a French or Italian loaf with a crispy crust and holey, airy interior works beautifully. The bread should be at least a day old, and even two or three days old is fine. In fact, slightly stale bread is actually preferable to fresh because it has less moisture and will crisp up more readily in the oven without burning on the outside while remaining soft inside. If you only have fresh bread, you can leave it out uncovered at room temperature for several hours or even overnight to dry it out, or you can cut it into cubes and leave it spread on a baking sheet to air dry. Using a serrated bread knife, cut the bread into approximately 1-inch cubes - consistency in size is important for even cooking. If the pieces vary too much, smaller ones will burn while larger ones remain soft. Don''t stress about making them perfectly geometric; slightly irregular, rustic-looking cubes are perfectly fine and actually have more character than machine-perfect cubes. As you cut, the bread may shed quite a few crumbs - this is normal with crusty bread. You can either discard these small crumbs or keep them separate to make breadcrumbs for another use, but don''t include them with your croutons as they''ll burn quickly in the oven. You should have about 4-5 cups of bread cubes, though you can make more or less depending on how many croutons you like in your salad.'),
  (14, 5, 2, 'Season', 'The seasoning step is where you transform plain bread cubes into flavor-packed croutons that contribute significantly to the overall taste of your Caesar salad, not just texture, and taking time to properly season and coat every piece will make a huge difference in the final result. Place your bread cubes in a large bowl - you want plenty of room to toss them without crushing. Drizzle generously with good quality olive oil - you need enough to lightly coat each cube without making them soggy or greasy. Start with about 1/4 cup and add more if needed. The oil serves multiple purposes: it helps the seasonings stick, it conducts heat to create crispy edges, and it adds its own flavor. Use your hands to toss the bread cubes, working to coat each piece evenly with oil. Your hands are the best tool for this job as they allow you to feel which pieces need more oil and ensure even distribution. Now for the garlic - this is one of the flavor highlights of homemade croutons. Mince 2-3 cloves of garlic very finely. You want small pieces that will distribute evenly rather than big chunks that will burn or create hot spots of garlic flavor. Add the minced garlic to the oiled bread cubes. Season with salt - more than you think you need as some will fall off during baking and salads generally need more seasoning than you expect. Add freshly ground black pepper for a touch of heat and complexity. Some people like to add other seasonings like dried oregano, basil, or Italian seasoning blend, though purists keep it simple with just garlic, salt, and pepper. Toss everything together thoroughly with your hands, rubbing the garlic and seasonings into the bread cubes, making sure every piece is coated with oil and speckled with garlic and seasonings. The cubes should glisten with oil but not be dripping, and you should see flecks of garlic on most pieces.'),
  (15, 5, 3, 'Bake', 'The baking process requires attention and occasional stirring to achieve croutons that are evenly golden and crispy throughout, not just on the surface, with a satisfying crunch that holds up even after being tossed with dressing and sitting for a few minutes in the salad. Preheat your oven to 375°F - this moderate temperature allows the croutons to dry out and crisp up throughout without burning on the outside before the interior is done. Spread your seasoned bread cubes in a single layer on a large baking sheet. If they''re crowded or piled on top of each other, they''ll steam rather than crisp, so use two baking sheets if necessary. The cubes should have some space between them for air circulation. Place the baking sheet in the preheated oven on the middle rack. Set a timer for 6 minutes. After 6 minutes, remove the pan from the oven and use a spatula to toss and turn the croutons, redistributing them on the pan so pieces that were in the corners move to the center and vice versa. This ensures even browning. Return to the oven and bake for another 6-9 minutes, checking frequently. The croutons are done when they''re golden brown all over - you should see no white or pale spots remaining - and they should feel hard and crispy when you press on them, not soft or yielding at all. They should sound hollow when you tap them. If you break one open, the interior should be completely dry and crispy, not soft or doughy. The edges and corners will be darker brown than the centers, which is normal and desirable - those darker bits provide concentrated flavor. The minced garlic will have toasted and become golden and aromatic, infusing the croutons with its flavor. Remove from the oven and let the croutons cool completely on the baking sheet - they''ll actually crisp up even more as they cool. Don''t be tempted to use them warm as they won''t have reached their final, crispiest texture yet. Once completely cool, they can be stored in an airtight container at room temperature for up to a week, though they''re best used within 2-3 days.'),

  -- Section 6: Assemble Salad (Recipe 2: Grandma's Secret Meatballs - PRIVATE)
  (16, 6, 1, 'Prepare Lettuce', 'The lettuce preparation is foundational to a great Caesar salad, and while it might seem straightforward, attention to detail in washing, drying, and cutting the romaine makes the difference between a sad, wilted salad and a crisp, refreshing one that perfectly carries the rich dressing and crunchy croutons. Start with 2-3 heads of romaine lettuce, depending on how many servings you need. Look for romaine that''s fresh and crisp with no brown spots or wilting - the leaves should be firm and snap rather than bend when you hold them horizontally. Remove any damaged or very dark outer leaves. Separate the remaining leaves from the core, rinse them thoroughly under cold running water, paying special attention to the base of each leaf where dirt tends to collect. Romaine can harbor quite a bit of grit, especially in the folds near the core, so thorough rinsing is important. Once rinsed, you face the crucial drying step - this is absolutely essential and cannot be skipped or rushed. Water on lettuce leaves will dilute your carefully made dressing, making it watery and preventing it from clinging properly to the leaves. The best tool for drying lettuce is a salad spinner - load the wet leaves into the basket, spin vigorously, pour out the water, and spin again. Repeat until no more water collects in the bottom of the spinner. If you don''t have a salad spinner, you can dry leaves by laying them on clean kitchen towels, rolling the towels gently, and pressing to absorb water, then spreading them out to air dry for a bit. The leaves should feel completely dry when you touch them - no moisture at all. Now for the tearing: tear the leaves into bite-sized pieces with your hands rather than cutting them with a knife. Tearing creates irregular edges that hold dressing better than clean knife cuts, and it prevents the edges from browning as quickly. The outer, darker leaves can be torn into smaller pieces, while the tender pale inner leaves can be left larger. You want a mix of sizes for textural interest. Place all the torn lettuce in a large salad bowl - you need a bowl much larger than you think to give yourself room to toss the salad properly without spilling.'),
  (17, 6, 2, 'Toss', 'The tossing technique is where many home cooks go wrong with Caesar salad - either under-dressing and leaving dry leaves, or over-dressing and creating a soup, or failing to coat evenly so some leaves are naked while others are drowning in dressing - but with the right approach, you can achieve perfect distribution and coating on every leaf. Start by adding about two-thirds of your prepared dressing to the bowl with the dry lettuce leaves. The reason for adding gradually is that different lettuces absorb dressing differently, and you can always add more but can''t remove excess. Now comes the tossing itself - there are several techniques that work. The traditional method uses two large spoons or salad tongs, lifting the lettuce from the bottom and folding it over the top repeatedly, turning the bowl as you work to reach all the leaves. Continue this motion for at least a full minute - yes, a full minute - to ensure every leaf gets coated. A more hands-on approach, and honestly the most effective, is to use your hands like a pair of salad forks, diving to the bottom of the bowl, grabbing a big handful of lettuce, lifting it up, and letting it fall back while gently rubbing the leaves between your fingers to distribute the dressing. Repeat this motion, working your way around the bowl, until every leaf glistens with dressing. Pick up a leaf and examine it - it should have a thin, even coating of dressing on all surfaces. If you see dry, white spots, keep tossing. If you still have leaves that seem under-dressed after a minute of tossing, add a bit more dressing and toss again. The leaves should look glossy but not dripping, and when you lift a handful, they should want to stick together slightly from the creamy dressing rather than falling apart like dry leaves. Taste a leaf - it should be well-seasoned with a good balance of creamy richness and bright acidity. If the flavor seems flat, you might need more dressing, or your dressing itself might need more salt or lemon juice.'),
  (18, 6, 3, 'Garnish', 'The final garnishing is what elevates a good Caesar salad to a great one, adding those crucial finishing touches that provide textural contrast, visual appeal, and final bursts of flavor that tie everything together into a cohesive, craveable dish. Start by adding your cooled, crispy croutons to the dressed lettuce. Don''t add all of them - reserve some of the nicest looking ones for the top so they showcase well and stay extra crispy. Toss the salad gently one more time to distribute the croutons throughout without crushing them. You want them nestled among the leaves rather than all sinking to the bottom. Now for the cheese - authentic Caesar salad uses Parmigiano-Reggiano, and it should be freshly shaved or grated, never the pre-grated stuff in a can or plastic tub. Buy a chunk of real Parmigiano-Reggiano - look for the authentic stamping on the rind - and use a vegetable peeler to shave thin, wide curls directly over the salad. These dramatic cheese curls look beautiful and have a wonderful texture, melting on your tongue and providing salty, umami richness without overwhelming the other flavors. Alternatively, you can use a microplane or fine grater to grate a fine snow of cheese over the salad - this distributes more evenly and gives every bite some cheese, though it''s less visually striking than the curls. Be generous with the cheese - you want at least 1/2 cup, possibly more. Add most of it, reserving some for garnish on top. Toss very gently one final time to incorporate the cheese. Transfer the salad to individual serving plates or bowls, or present it in a large serving bowl for family-style dining. Top with your reserved croutons, positioned artfully on top where they''ll stay crispiest. Add a final shower of cheese shavings over the top. Crack fresh black pepper generously over everything - the coarse grind and pungent flavor of freshly cracked pepper is essential to the Caesar flavor profile. Some modern presentations add a halved soft-boiled egg or grilled chicken on top, though this moves away from the traditional version. Serve immediately before the croutons start to soften, with extra dressing on the side for anyone who likes their salad more heavily dressed. Each forkful should deliver crispy lettuce, creamy dressing, crunchy croutons, salty cheese, and pungent pepper all at once.'),

  -- Section 7: Prepare Beef and Duxelles (Recipe 3: Spaghetti Carbonara)
  (19, 7, 1, 'Sear Beef', 'The initial searing of the beef tenderloin is perhaps the most critical step in the entire Beef Wellington process, as it develops the deep, caramelized crust that provides concentrated flavor and creates a barrier that helps keep the interior juicy while the pastry bakes. Select a premium center-cut beef tenderloin, about 2 pounds, which should be trimmed of all silver skin and external fat by your butcher or yourself using a sharp boning knife. The tenderloin should be roughly cylindrical and even in thickness - if one end is significantly thinner than the other, you may want to fold it under and tie it to create a more uniform shape for even cooking. Bring the beef to room temperature about 30 minutes before searing - cold meat straight from the refrigerator will lower the pan temperature drastically and prevent proper browning. Pat the beef completely dry with paper towels, as any surface moisture will create steam and prevent the Maillard reaction from occurring. Season the entire surface generously with coarse salt and freshly ground black pepper, pressing the seasonings into the meat. Heat a large, heavy skillet - preferably cast iron - over high heat until it''s smoking hot. Add a tablespoon of oil with a high smoke point like grapeseed or vegetable oil. Carefully place the beef in the pan and resist the urge to move it. Let it sear undisturbed for exactly 2 minutes, allowing a deep golden-brown crust to develop. Using tongs, turn the beef to an adjacent side and sear for another 2 minutes. Continue rotating until all sides are beautifully browned - this usually takes about 8 minutes total for a typical tenderloin. The goal is not to cook the beef through, just to develop that flavorful crust on every surface. Remove immediately and transfer to a plate to cool completely before proceeding.'),
  (20, 7, 2, 'Make Duxelles', 'Creating the perfect duxelles requires patience and attention as you transform ordinary mushrooms into a concentrated, intensely flavored paste that will add moisture, umami depth, and earthy richness to your Beef Wellington. Start with about 1 pound of mixed mushrooms - a combination of cremini, shiitake, and porcini works beautifully, offering different textural and flavor notes. If using dried porcini, rehydrate them in hot water first, squeeze out excess moisture, and chop along with the fresh mushrooms. Clean the mushrooms by wiping them with a damp paper towel rather than rinsing them under water, which would add unwanted moisture. Remove any tough stems, especially from shiitakes. Now comes the crucial chopping: you need to mince these mushrooms extremely finely, almost to a paste. You can do this with a sharp chef''s knife on a cutting board, taking your time to make smaller and smaller pieces, or you can pulse them in a food processor - but be careful not to over-process them into a puree. The goal is a finely minced texture where individual pieces are barely visible. Heat butter in a large skillet over medium-high heat. Add finely minced shallots first, cooking until softened and fragrant. Add your minced mushrooms all at once - the pan will seem very full, but the mushrooms will release their liquid and shrink dramatically. Cook, stirring frequently, as the mushrooms release their moisture. Keep cooking and stirring, allowing all that liquid to evaporate completely. This is critical - any remaining moisture will make your pastry soggy. The mixture should go from wet and steamy to dry and crumbly, changing from gray-brown to darker brown as it concentrates. This can take 15-20 minutes. Add fresh thyme leaves, salt, and pepper. The finished duxelles should be deeply colored, completely dry, aromatic, and intensely flavored. Transfer to a bowl and cool completely.'),
  (21, 7, 3, 'Cool Both', 'The cooling step might seem like mere waiting, but it''s absolutely essential for the success of your Beef Wellington and cannot be rushed or skipped, as assembling with warm components will lead to melted butter in your pastry, soggy layers, and potential food safety issues. Transfer your seared beef to a plate and place it in the refrigerator, uncovered. The beef needs to be completely cold to the touch before you proceed to wrapping - this typically takes at least 30 minutes, and up to an hour is even better. As it cools, any residual heat in the center will dissipate, and the surface will firm up slightly, making it easier to handle during the wrapping process. The cold beef will also help keep your puff pastry cold during assembly, which is crucial for achieving those beautiful, distinct flaky layers when it bakes. While the beef chills, spread your duxelles in a thin layer on a plate or baking sheet and place it in the refrigerator as well. Hot or even warm duxelles will melt the butter in your puff pastry, creating a greasy mess rather than flaky layers. The duxelles should be completely cold and firm to the touch before use. Some cooks even make the duxelles a day ahead and refrigerate it overnight, which gives the flavors time to meld and ensures it''s thoroughly chilled. If you''re in a hurry, you can spread the duxelles in a thin layer and place it in the freezer for about 10 minutes to speed up the cooling process, but watch carefully that it doesn''t freeze solid. Use this waiting time productively - prepare your prosciutto and puff pastry, make your egg wash, set up your work station with plastic wrap and any other tools you''ll need. When both components are completely cold - and I mean truly cold, not just cool - you''re ready to move on to the assembly process. Some professional chefs even freeze the seared beef for 30 minutes to ensure it''s absolutely cold throughout, though this isn''t strictly necessary for home cooks as long as you''re patient with the refrigeration.'),

  -- Section 8: Wrap in Pastry (Recipe 3: Spaghetti Carbonara)
  (22, 8, 1, 'Layer Prosciutto', 'The prosciutto layer serves multiple crucial functions in Beef Wellington - it creates a moisture barrier between the wet duxelles and the delicate puff pastry, adds its own savory, salty flavor dimension, and helps hold everything together in a neat, cohesive package that''s easier to wrap in pastry. Lay out a large sheet of plastic wrap on your work surface, approximately 18 inches long. You''ll need about 12-16 slices of thinly sliced prosciutto di Parma or similar high-quality Italian prosciutto. The slices should be paper-thin - if your deli cuts them too thick, ask them to adjust their slicer or find a different source. Arrange the prosciutto slices on the plastic wrap in a slightly overlapping pattern, creating a rectangle that''s large enough to fully encase your beef tenderloin with a bit of overlap. Orient the slices so they run parallel to the long edge of the work surface - you want to be able to roll the beef away from you. The slices should overlap by about 1/4 to 1/2 inch, with no gaps where the duxelles could seep through. Think of it like shingling a roof - each slice should cover part of the previous one. The rectangle should be roughly 10 inches wide by 12 inches long, though exact dimensions depend on your beef size. Pat the prosciutto with paper towels to remove any excess moisture on the surface. Some of the slices may be slightly sticky and want to fold over themselves - take your time to lay them out flat and smooth. This prosciutto blanket will become the inner wrapping that holds the duxelles in place and prevents the pastry from getting soggy. Don''t skimp on the prosciutto coverage - any bare spots could allow moisture to escape and create problems. Once your prosciutto rectangle is perfect and complete, you''re ready for the next step.'),
  (23, 8, 2, 'Add Duxelles and Beef', 'This assembly step requires organization, quick work, and a gentle touch to create that perfect cylindrical package where all the components are tightly wrapped together without any air pockets or gaps that could cause problems during baking. Retrieve your completely cooled duxelles from the refrigerator. Using an offset spatula or the back of a spoon, spread the duxelles in an even layer over your prosciutto blanket, leaving about a 1-inch border around all edges. The layer should be fairly thin and uniform - you want enough to flavor every slice but not so much that it squishes out when you roll. Press down gently as you spread to help the duxelles adhere to the prosciutto. Remove your cold seared beef from the refrigerator and place it lengthwise across the bottom third of the prosciutto and duxelles rectangle, with one long edge of the beef about 2 inches from the bottom edge of the prosciutto. Now comes the rolling: using the plastic wrap as a guide, lift the bottom edge of the prosciutto and fold it up and over the beef, pressing gently to help it adhere. Continue rolling the beef away from you, using the plastic wrap to help guide and tighten the roll, keeping constant gentle pressure to create a tight cylinder with no air pockets. The prosciutto and duxelles should wrap completely around the beef with a slight overlap - if there are any gaps, unroll slightly and adjust before proceeding. Once fully rolled, twist the ends of the plastic wrap tightly like a candy wrapper, creating a neat, tight cylinder. The twisting helps compress everything together and shapes the package. Refrigerate this wrapped bundle for at least 30 minutes, up to an hour. This chilling step firms everything up and makes the next wrapping step much easier. The prosciutto will adhere to the duxelles and beef, creating one cohesive package.'),
  (24, 8, 3, 'Wrap in Puff Pastry', 'The puff pastry wrapping is the final and most visible layer of your Beef Wellington, and proper technique here is essential for achieving that stunning golden crust with clearly defined flaky layers and no soggy bottom or torn spots that would mar the presentation. Remove your puff pastry from the refrigerator about 10 minutes before working with it - it should be cold but pliable enough to roll without cracking. If using frozen puff pastry, thaw it in the refrigerator overnight, never at room temperature. Lightly flour your work surface and rolling pin. Unfold or unroll the puff pastry and roll it out into a rectangle large enough to fully encase your beef bundle with some overlap - typically about 12 inches by 14 inches, depending on your beef size. Roll evenly, rotating the dough occasionally and adding flour as needed to prevent sticking, but use flour sparingly as too much will inhibit the layers from separating properly during baking. The pastry should be about 1/8 to 1/4 inch thick - thick enough to not tear but thin enough to cook through completely. Trim any ragged edges with a sharp knife to create a neat rectangle. Prepare an egg wash by whisking together 1 egg with 1 tablespoon of water until completely smooth. Remove your prosciutto-wrapped beef from the refrigerator and unwrap it from the plastic wrap. Place it seam-side down in the center of your pastry rectangle. Brush all edges of the pastry with egg wash - this acts as glue to seal the seams. Fold the short ends of the pastry over the beef first, trimming excess if needed but leaving enough to fully cover the ends. Then lift one long edge of the pastry and fold it over the beef, stretching it slightly if needed to create a taut wrap. Brush this edge with more egg wash, then fold the other long edge over, overlapping slightly and pressing firmly to seal. The seam should run along the bottom of your Wellington. Trim any excess pastry, especially at the ends, and crimp the edges decoratively if desired. The whole package should be neat, smooth, and completely encased in pastry with no visible gaps or tears. If you notice any cracks or tears, patch them with scraps of pastry, brushing with egg wash to adhere.'),

  -- Section 9: Bake to Perfection (Recipe 3: Spaghetti Carbonara)
  (25, 9, 1, 'Chill', 'The final chilling period before baking serves multiple important purposes that will significantly impact the quality and appearance of your finished Beef Wellington, making it worth the wait even though you''re anxious to get this showstopper into the oven. Carefully transfer your wrapped Wellington to a baking sheet lined with parchment paper, placing it seam-side down. The parchment prevents sticking and makes cleanup easier. Place the entire baking sheet in the refrigerator and chill for at least 30 minutes, though 45 minutes to an hour is even better if you have the time. During this chilling period, several beneficial things are happening: First, the pastry is firming back up after being handled and warmed by your hands during wrapping. Cold pastry produces the best layers and puff - if the butter in the pastry is too warm when it goes into the oven, it will melt and leak out before the layers have a chance to separate and create that characteristic flaky texture. Second, the egg wash on your seals is drying slightly, creating a better bond that''s less likely to open during baking. Third, all your layers are adhering to each other and settling into place, reducing the chance of shifting or gaps during baking. Fourth, and perhaps most importantly from a food safety perspective, the beef is staying cold, which means it will take longer to cook through and is less likely to overcook while you wait for the pastry to brown. This chilling step is especially important if your kitchen is warm. While the Wellington chills, preheat your oven to 425°F. This high temperature is necessary to create steam quickly, which causes the puff pastry layers to separate dramatically, creating that light, crispy texture we''re aiming for. Make sure your oven rack is positioned in the center of the oven for even heat circulation. Use this time to prepare any side dishes you''re planning to serve with your Wellington. When the chilling time is up and your oven is fully preheated, you''re ready for the final preparations before baking.'),
  (26, 9, 2, 'Brush and Score', 'These final decorative touches transform your Beef Wellington from a simple wrapped package into an elegant centerpiece worthy of special occasions, while also serving functional purposes that improve the cooking and final presentation. Remove your chilled Wellington from the refrigerator. Prepare fresh egg wash if your previous batch has thickened or dried out - whisk together 1 egg with 1 tablespoon water until smooth and completely combined with no streaks of white or yolk visible. Using a pastry brush, gently but thoroughly brush the entire surface of the pastry with egg wash. Apply a thin, even coat - too much will pool and create dark blotches, while too little won''t give you that beautiful golden sheen. Make sure to cover every visible surface, including the sides, but avoid letting egg wash drip down onto your parchment paper where it will burn. Let this first coat dry for about 2 minutes, then apply a second coat for extra insurance of that gorgeous golden-brown finish. Now comes the decorative scoring: using a sharp paring knife, carefully score the surface of the pastry in a decorative pattern. Traditional options include a diamond cross-hatch pattern, diagonal parallel lines running the length of the Wellington, or a herringbone pattern. Whatever design you choose, cut just through the top layer of pastry - you want to score deep enough to be visible after baking but not so deep that you pierce through to the meat or create weak points where the pastry might tear. These scored lines will separate slightly during baking as the pastry puffs, creating an attractive textured appearance on the golden surface. The scoring also serves a functional purpose, making it easier to slice through the pastry later when serving. Finally, use the tip of your knife to poke 3-4 small holes or vents in the top of the Wellington. These allow steam to escape during baking, preventing the pastry from becoming soggy inside. Place the holes in inconspicuous spots or incorporate them into your decorative pattern if possible.'),
  (27, 9, 3, 'Bake', 'The baking phase is the culmination of all your careful preparation and requires precise timing and temperature management to achieve that perfect combination of golden, flaky pastry exterior and properly cooked beef interior with no gray band of overcooked meat. Place your prepared Wellington in the preheated 425°F oven on the center rack. Set your timer for 25 minutes. During this time, resist the temptation to open the oven door, as this releases heat and steam that are crucial for proper puff pastry development. After 25 minutes, begin checking the Wellington. The pastry should be developing good color - a deep golden brown with the scored lines clearly visible and the surface starting to look shiny and crisp. If it''s not quite there yet, continue baking and check every 3-5 minutes. While color is one indicator, the most reliable way to know when your Wellington is done is internal temperature. Insert an instant-read thermometer horizontally into the center of the beef, pushing through the pastry and going about 2 inches deep into the meat. For medium-rare, which is ideal for beef tenderloin, you''re looking for an internal temperature of 120-125°F. Remember that the beef will continue to cook as it rests, gaining another 5-10 degrees, so pulling it at 125°F will result in a final temperature of about 130-135°F, perfect medium-rare. If you prefer medium, aim for an internal temperature of 130-135°F before resting. Keep in mind that cooking times can vary based on your oven, the thickness of your beef, how cold it was when it went in, and even humidity. The 25-30 minute estimate is a guideline, not a rule. When the Wellington reaches your target temperature and the pastry is beautifully golden brown all over with no pale or doughy-looking spots, remove it from the oven. Transfer the entire Wellington, still on its parchment paper, to a cutting board. This is crucial: let it rest for at least 10 minutes, and preferably 15 minutes, before slicing. During this resting period, the meat fibers relax and reabsorb their juices, preventing them from running out when you cut into the Wellington. The pastry also firms up slightly, making for cleaner slices. Cover loosely with foil if you''re worried about it cooling too much, though it will stay quite hot inside. When ready to serve, use a sharp serrated knife to cut the Wellington into thick slices, about 1-1.5 inches each. Wipe the blade between cuts for clean presentation. Each slice should reveal beautiful concentric layers: golden brown puff pastry, a thin layer of prosciutto, dark duxelles, and perfectly pink beef in the center. This is an impressive sight that makes all the effort completely worthwhile.'),

  -- Section 10: Make Mascarpone Cream (Recipe 4: Mom's Chocolate Cake - PRIVATE)
  (28, 10, 1, 'Beat Egg Yolks', 'Separate six eggs carefully, ensuring no yolk gets into the whites. Place yolks in a large bowl and add three-quarters cup granulated sugar. Using an electric mixer on medium-high speed, beat the mixture for about three to four minutes until it becomes thick, pale yellow, and forms ribbons when the beaters are lifted.'),
  (29, 10, 2, 'Fold Mascarpone', 'Add sixteen ounces of room temperature mascarpone cheese to the beaten egg yolk mixture. Using a large rubber spatula, gently fold the mascarpone into the yolks using a figure-eight motion, rotating the bowl as you work. Continue folding until the mixture is completely smooth and homogeneous with no streaks or lumps remaining.'),
  (30, 10, 3, 'Whip Cream', 'In a separate chilled bowl, whip one cup of heavy cream to soft peaks using clean beaters. The cream should hold its shape but still be slightly droopy. Gently fold the whipped cream into the mascarpone mixture in two additions, being careful not to deflate the cream. The final mixture should be light and airy.'),

  -- Section 11: Soak Ladyfingers (Recipe 4: Mom's Chocolate Cake - PRIVATE)
  (31, 11, 1, 'Make Coffee', 'Brew two cups of strong espresso using freshly ground coffee beans for maximum flavor. If you don''t have an espresso machine, use very strong brewed coffee. Let it cool to room temperature, then stir in three tablespoons of coffee liqueur such as Kahlua or Marsala wine for authentic Italian flavor and depth.'),
  (32, 11, 2, 'Dip Quickly', 'Working one at a time, quickly dip each ladyfinger cookie into the coffee mixture for exactly two to three seconds per side. The cookies should be saturated but not falling apart. Move with purpose and develop a rhythm: dip, flip, dip, and immediately place in your dish. Don''t let them soak or they''ll disintegrate.'),
  (33, 11, 3, 'Layer in Dish', 'Arrange the coffee-soaked ladyfingers in a tight single layer across the bottom of a nine-by-thirteen inch dish, fitting them like puzzle pieces. Break some cookies as needed to fill gaps and ensure complete coverage with no spaces where cream could seep through. The layer should be snug and even.'),

  -- Section 12: Layer and Chill (Recipe 4: Mom's Chocolate Cake - PRIVATE)
  (34, 12, 1, 'Add Cream', 'Using an offset spatula, spread half of the mascarpone cream mixture evenly over the layer of soaked ladyfingers. Work gently to avoid disturbing the cookies underneath. Make sure the cream extends all the way to the edges and corners, creating an even layer about one inch thick across the entire surface.'),
  (35, 12, 2, 'Repeat Layers', 'Create a second layer of coffee-soaked ladyfingers directly on top of the cream layer, again arranging them tightly and breaking pieces to fill gaps. Spread the remaining mascarpone cream over this second cookie layer, smoothing the top with your spatula into an even, level surface for the cocoa powder topping.'),
  (36, 12, 3, 'Dust and Chill', 'Using a fine-mesh sieve, generously dust the entire top surface with unsweetened cocoa powder until the cream is completely covered and looks chocolate brown. Cover tightly with plastic wrap and refrigerate for at least six hours or overnight, allowing the flavors to meld and the cookies to soften to perfect consistency.'),

  -- Section 13: Make Tomato Base (Recipe 5: Margherita Pizza)
  (37, 13, 1, 'Sauté Vegetables', 'Heat two tablespoons of olive oil in a large deep skillet over medium heat. Add one finely diced yellow onion and one diced red bell pepper to the hot oil. Cook, stirring occasionally, for about five minutes until the vegetables soften and the onion becomes translucent without browning.'),
  (38, 13, 2, 'Add Spices', 'Sprinkle one teaspoon ground cumin, one teaspoon smoked paprika, and a quarter teaspoon cayenne pepper over the softened vegetables. Stir continuously for one minute, allowing the spices to toast and release their aromatic oils, which will deepen the flavor of the entire dish significantly.'),
  (39, 13, 3, 'Add Tomatoes', 'Pour a twenty-eight ounce can of crushed tomatoes into the spiced vegetable mixture. Stir well to combine all ingredients, then reduce heat to medium-low. Let the tomato sauce simmer gently for fifteen minutes, stirring occasionally, until it thickens slightly and the flavors meld together beautifully.'),

  -- Section 14: Poach Eggs (Recipe 5: Margherita Pizza)
  (40, 14, 1, 'Create Wells', 'Using the back of a large spoon, create six evenly spaced indentations or wells in the thickened tomato sauce. Make each well deep enough to hold an egg without overflowing, pressing gently but firmly to create distinct pockets that will cradle the eggs during cooking.'),
  (41, 14, 2, 'Add Eggs', 'Crack one egg into a small bowl first, then gently slide it into one of the prepared wells in the sauce. Repeat this process with five more eggs, placing one in each well. This careful method prevents broken yolks and ensures each egg stays in its designated spot.'),
  (42, 14, 3, 'Cover and Cook', 'Cover the skillet tightly with a lid to trap steam inside, which will help cook the egg whites. Reduce heat to low and cook for eight to ten minutes, checking occasionally. The egg whites should be completely set and opaque while the yolks remain gloriously runny.'),

  -- Section 15: Finish and Serve (Recipe 5: Margherita Pizza)
  (43, 15, 1, 'Check Doneness', 'Carefully remove the lid and gently jiggle the pan to test the eggs. The whites should be firm and no longer translucent, while the yolks should still wobble slightly, indicating they remain soft and runny inside. If needed, cook for another minute or two with the lid on.'),
  (44, 15, 2, 'Garnish', 'Remove from heat and immediately sprinkle the shakshuka generously with fresh chopped cilantro, flat-leaf parsley, and crumbled feta cheese. The herbs add brightness while the feta provides tangy creaminess that perfectly complements the rich tomato sauce and eggs. Add a pinch of flaky salt if desired.'),
  (45, 15, 3, 'Serve', 'Bring the hot skillet directly to the table for a beautiful rustic presentation. Serve immediately with plenty of crusty bread, warm pita, or challah for dipping into the runny yolks and flavorful sauce. Each person should get at least one egg with plenty of sauce.'),

  -- Section 16: Mix Meatball Ingredients (Recipe 6: Nonna's Pasta Sauce - PRIVATE)
  (46, 16, 1, 'Combine Meats', 'In a large bowl, gently combine one pound ground beef, half pound ground pork, and half pound ground veal with one cup fresh breadcrumbs, two beaten eggs, and Grandma''s secret spice blend. Mix just until combined, being careful not to overwork the meat which would make tough meatballs.'),
  (47, 16, 2, 'Season and Rest', 'Add three cloves minced garlic, half cup grated Parmesan, quarter cup fresh parsley, and the proprietary family spice blend to the meat mixture. Season with salt and pepper, then cover and refrigerate for thirty minutes. This resting time allows flavors to meld and makes shaping easier.'),

  -- Section 17: Shape and Simmer (Recipe 6: Nonna's Pasta Sauce - PRIVATE)
  (48, 17, 1, 'Form and Brown', 'With lightly moistened hands, gently roll the meat mixture into two-inch balls, handling them as little as possible. Heat olive oil in a large skillet and brown the meatballs in batches, turning carefully to develop a rich crust on all sides without breaking them apart.'),
  (49, 17, 2, 'Simmer', 'Transfer the browned meatballs to a pot of simmering tomato sauce. Cover and cook on low heat for two hours, allowing the meatballs to become incredibly tender while infusing the sauce with their rich, meaty flavor. Stir occasionally but gently to prevent breaking them apart.'),

  -- Section 18: Prep Ingredients (Recipe 7: Thai Green Curry)
  (50, 18, 1, 'Dice Pancetta', 'Remove the rind from eight ounces of pancetta and cut the meat into quarter-inch cubes. The small size ensures each piece will crisp up nicely and distribute evenly throughout the pasta. Keep refrigerated until ready to cook to maintain freshness and make handling easier.'),
  (51, 18, 2, 'Mix Egg Mixture', 'Crack four large eggs into a medium bowl and whisk until smooth. Add one cup freshly grated Pecorino Romano cheese and generous amounts of coarsely ground black pepper. Whisk vigorously until well combined into a thick, creamy mixture that will coat the pasta beautifully.'),
  (52, 18, 3, 'Boil Water', 'Fill a large pot with water, add a generous amount of salt until it tastes like the sea, and bring to a rolling boil over high heat. The pasta will need plenty of room to move freely, and the well-salted water is your only chance to season it properly.'),

  -- Section 19: Cook Pasta and Pancetta (Recipe 7: Thai Green Curry)
  (53, 19, 1, 'Cook Spaghetti', 'Add one pound of spaghetti to the boiling water and cook according to package directions until al dente, with a slight bite. Before draining, use a measuring cup to reserve at least one cup of the starchy pasta cooking water, which will help create a silky sauce.'),
  (54, 19, 2, 'Crisp Pancetta', 'While pasta cooks, add the diced pancetta to a large cold skillet and place over medium heat. Cook, stirring occasionally, until the fat renders out and the pieces become golden brown and crispy, about eight to ten minutes. No additional oil is needed as the pancetta releases plenty.'),
  (55, 19, 3, 'Remove from Heat', 'Turn off the heat under the pancetta pan immediately when the pasta is done. Let the pan sit and cool for one to two minutes. This crucial step prevents the eggs from scrambling when added, ensuring a creamy sauce rather than chunky scrambled eggs.'),

  -- Section 20: Combine and Toss (Recipe 7: Thai Green Curry)
  (56, 20, 1, 'Add Pasta', 'Using tongs, transfer the drained spaghetti directly from the pot into the pancetta pan with rendered fat. Toss vigorously to coat every strand with the flavorful pancetta fat. The residual pasta water clinging to the noodles will help create the sauce base.'),
  (57, 20, 2, 'Add Egg Mixture', 'With the pan still off the heat, quickly pour the egg and cheese mixture over the hot pasta. Toss continuously and rapidly, lifting and turning the pasta to distribute the eggs evenly. The residual heat will gently cook the eggs into a silky, creamy sauce coating every strand.'),
  (58, 20, 3, 'Adjust Consistency', 'If the sauce seems too thick or clumpy, add reserved pasta water one splash at a time, tossing constantly until you achieve a glossy, creamy consistency that coats the pasta without pooling. Serve immediately in warm bowls with extra Pecorino and black pepper on top.'),

  -- Section 21: Marinate Chicken (Recipe 8: Uncle's BBQ Sauce - PRIVATE)
  (59, 21, 1, 'Cut Chicken', 'Cut two pounds of boneless, skinless chicken breast into uniform one-inch cubes. Consistent sizing ensures even cooking and proper absorption of marinade. Pat the chicken pieces dry with paper towels before marinating, as excess moisture will dilute the marinade and prevent proper flavor penetration.'),
  (60, 21, 2, 'Make Marinade', 'In a large bowl, whisk together one cup plain yogurt, two tablespoons grated fresh ginger, four minced garlic cloves, one tablespoon garam masala, one teaspoon ground cumin, and one teaspoon paprika. Add salt to taste and mix until smooth and well combined into a flavorful marinade.'),
  (61, 21, 3, 'Marinate', 'Add the chicken cubes to the yogurt marinade and toss until every piece is thoroughly coated. Cover the bowl tightly with plastic wrap and refrigerate for at least four hours, or up to twenty-four hours for maximum flavor. The yogurt tenderizes the chicken while infusing it with spices.'),

  -- Section 22: Grill Chicken (Recipe 8: Uncle's BBQ Sauce - PRIVATE)
  (62, 22, 1, 'Preheat', 'Preheat your broiler to high heat or prepare your outdoor grill for direct high-heat cooking. If using a broiler, position the oven rack about six inches from the heating element. If using wooden skewers, soak them in water for thirty minutes beforehand to prevent burning.'),
  (63, 22, 2, 'Thread Skewers', 'Thread the marinated chicken pieces onto skewers, leaving small spaces between each piece to ensure even cooking and proper heat circulation. Shake off excess marinade to prevent dripping and smoking. Arrange skewers on a foil-lined baking sheet or directly on the grill grates, brushing lightly with oil.'),
  (64, 22, 3, 'Cook', 'Grill or broil the chicken skewers for twelve to fifteen minutes total, turning every three to four minutes to ensure even cooking and attractive char marks on all sides. The chicken should develop dark, slightly charred spots while remaining juicy inside, reaching an internal temperature of one hundred sixty-five degrees.'),

  -- Section 23: Make Curry Sauce (Recipe 8: Uncle's BBQ Sauce - PRIVATE)
  (65, 23, 1, 'Sauté Aromatics', 'Melt three tablespoons butter in a large skillet over medium heat. Add one diced onion, one tablespoon grated ginger, and four minced garlic cloves. Cook, stirring frequently, for about five minutes until the onions turn soft and golden brown, filling your kitchen with incredible aromatics.'),
  (66, 23, 2, 'Add Spices and Tomatoes', 'Stir in one teaspoon garam masala, one teaspoon cumin, half teaspoon turmeric, and cook for one minute until fragrant. Add one can crushed tomatoes and one cup heavy cream, stirring to combine. Season with salt and bring to a gentle simmer, creating a rich, orange-hued sauce.'),
  (67, 23, 3, 'Simmer with Chicken', 'Remove the grilled chicken from skewers and add pieces to the simmering sauce. Reduce heat to low and cook for fifteen minutes, stirring occasionally, allowing the chicken to absorb the sauce flavors. Garnish generously with fresh cilantro and serve hot with basmati rice and warm naan bread.'),

  -- Section 24: Mix Batter (Recipe 9: Quinoa Salad)
  (68, 24, 1, 'Combine Dry', 'In a large mixing bowl, whisk together two cups all-purpose flour, two tablespoons granulated sugar, two teaspoons baking powder, and half teaspoon salt. Whisking thoroughly ensures the leavening agent is evenly distributed, which will give you consistently fluffy pancakes without any bitter pockets of baking powder.'),
  (69, 24, 2, 'Mix Wet', 'In a separate bowl, whisk together two cups buttermilk, two large eggs, and quarter cup melted butter that has cooled slightly. Beat until the eggs are fully incorporated and the mixture is smooth. The buttermilk provides tangy flavor and reacts with the baking powder for extra lift.'),
  (70, 24, 3, 'Fold Together', 'Pour the wet ingredients into the bowl with the dry ingredients. Using a rubber spatula or wooden spoon, gently fold the mixture together with just a few strokes until barely combined. The batter should be lumpy with visible streaks of flour remaining. Overmixing develops gluten and creates tough pancakes.'),

  -- Section 25: Cook Pancakes (Recipe 9: Quinoa Salad)
  (71, 25, 1, 'Heat Griddle', 'Preheat an electric griddle to three hundred seventy-five degrees Fahrenheit, or heat a large non-stick skillet over medium heat. Lightly grease the cooking surface with butter or oil, wiping away any excess with a paper towel. The surface is ready when a drop of water sizzles immediately.'),
  (72, 25, 2, 'Pour and Add Berries', 'Using a quarter-cup measure or ladle, pour batter onto the hot griddle, leaving space between pancakes for spreading. Immediately sprinkle a small handful of fresh blueberries onto the wet surface of each pancake. The berries will sink slightly as the batter begins to cook and set around them.'),
  (73, 25, 3, 'Flip', 'Watch for small bubbles to form across the surface of the pancakes and for the edges to look dry and set, which takes about two to three minutes. Slide a spatula underneath and flip quickly. Cook for two more minutes until golden brown on the second side and cooked through.'),

  -- Section 26: Serve Hot (Recipe 9: Quinoa Salad)
  (74, 26, 1, 'Stack', 'Transfer cooked pancakes to warm serving plates, stacking three to four pancakes per person. The warmth from the bottom pancakes will help melt the butter and syrup you add on top. Keep finished pancakes warm in a low oven if cooking in batches for a crowd.'),
  (75, 26, 2, 'Top', 'Place a generous pat of cold butter on top of each stack. The heat from the pancakes will slowly melt the butter, allowing it to cascade down the sides and soak into the fluffy layers, adding rich flavor and moisture. Let it sit for a moment to melt completely.'),
  (76, 26, 3, 'Drizzle', 'Drizzle warm pure maple syrup generously over each stack, allowing it to pool around the edges and soak into the pancakes. Top with additional fresh blueberries for color and freshness. Serve immediately while the pancakes are hot and the butter is still melting for the best texture and flavor.'),

  -- Section 27: Prepare Eggplant (Recipe 10: Dad's Chili Recipe - PRIVATE)
  (77, 27, 1, 'Slice', 'Trim the stems from two large globe eggplants and cut them into uniform quarter-inch thick rounds using a sharp knife. Try to keep the slices as even as possible so they cook at the same rate. Arrange the slices in a single layer on baking sheets lined with paper towels.'),
  (78, 27, 2, 'Salt', 'Generously sprinkle both sides of each eggplant slice with coarse salt. Let them sit undisturbed for thirty minutes at room temperature. The salt draws out moisture and bitterness, preventing the eggplant from becoming mushy or bitter in the final dish. Blot dry with paper towels before cooking.'),
  (79, 27, 3, 'Grill', 'Brush both sides of the dried eggplant slices with olive oil. Either grill them over medium-high heat or arrange on baking sheets and roast at four hundred degrees until golden brown on both sides, about four minutes per side. They should be tender and slightly caramelized.'),

  -- Section 28: Make Meat Sauce (Recipe 10: Dad's Chili Recipe - PRIVATE)
  (80, 28, 1, 'Brown Meat', 'Heat two tablespoons olive oil in a large skillet over medium-high heat. Add one and a half pounds ground lamb or beef, breaking it apart with a wooden spoon. Cook until deeply browned, about eight minutes. Add one diced onion and four minced garlic cloves, cooking until softened.'),
  (81, 28, 2, 'Add Seasonings', 'Stir in one teaspoon ground cinnamon, one tablespoon dried oregano, one can crushed tomatoes, and two tablespoons tomato paste. The cinnamon adds authentic Greek flavor while the oregano provides herbaceous notes. Season generously with salt and pepper, stirring well to combine all ingredients thoroughly.'),
  (82, 28, 3, 'Simmer', 'Reduce heat to medium-low and let the meat sauce simmer uncovered for thirty minutes, stirring occasionally. The sauce should thicken considerably and reduce, with the flavors melding together beautifully. Taste and adjust seasoning as needed. The sauce should be thick enough to hold its shape when layered.'),

  -- Section 29: Layer and Bake (Recipe 10: Dad's Chili Recipe - PRIVATE)
  (83, 29, 1, 'Layer Eggplant', 'Lightly oil a nine-by-thirteen inch baking dish. Arrange half of the cooked eggplant slices in a single overlapping layer covering the bottom of the dish completely. The slices should fit snugly together with minimal gaps, creating a solid base layer for the moussaka that will hold everything together.'),
  (84, 29, 2, 'Add Meat and Repeat', 'Spread all of the meat sauce evenly over the first eggplant layer, pressing down gently to create a compact, even layer. Top with the remaining eggplant slices, arranging them in another overlapping layer. Press down gently to compress the layers and create a neat, cohesive structure.'),
  (85, 29, 3, 'Top and Bake', 'Pour prepared béchamel sauce over the top eggplant layer, spreading it evenly to the edges and smoothing the surface. Sprinkle with grated Parmesan if desired. Bake at three hundred fifty degrees Fahrenheit for forty-five minutes until the top is golden brown and bubbling. Let rest fifteen minutes before cutting.'),

  -- Section 30: Make Shortbread Crust (Recipe 11: Lasagna Bolognese)
  (86, 30, 1, 'Mix Dough', 'In a large bowl, combine two cups all-purpose flour, half cup powdered sugar, and one cup softened butter cut into small pieces. Using your fingers or a pastry cutter, work the ingredients together until they form a cohesive, crumbly dough. The texture should resemble coarse sand.'),
  (87, 30, 2, 'Press', 'Transfer the crumbly dough to a nine-by-thirteen inch baking pan. Using your hands or the bottom of a measuring cup, press the dough firmly and evenly into the bottom of the pan, making sure to reach all corners. The layer should be compact and uniform thickness for even baking.'),
  (88, 30, 3, 'Bake', 'Bake the crust in a preheated three hundred fifty degree oven for eighteen to twenty minutes until it''s set and lightly golden around the edges, but not deeply browned. The center should look dry rather than wet. Remove from oven but keep the oven on for the next step.'),

  -- Section 31: Prepare Lemon Filling (Recipe 11: Lasagna Bolognese)
  (89, 31, 1, 'Whisk Eggs', 'In a medium bowl, crack four large eggs and add one and a half cups granulated sugar. Whisk vigorously for two to three minutes until the mixture becomes pale, thick, and frothy. This incorporates air and helps create a light texture in the finished lemon filling.'),
  (90, 31, 2, 'Add Lemon', 'Add half cup freshly squeezed lemon juice, the zest of two lemons grated finely, and quarter cup all-purpose flour to the egg mixture. Whisk thoroughly until completely smooth with no lumps remaining. The flour helps set the filling while the zest provides intense lemon flavor and the juice adds brightness.'),
  (91, 31, 3, 'Pour', 'Immediately pour the lemon filling over the hot crust straight from the oven. The heat helps the filling adhere to the crust and begin setting. Use a spatula to gently spread the filling to the edges if needed, ensuring even coverage across the entire surface.'),

  -- Section 32: Bake and Cool (Recipe 11: Lasagna Bolognese)
  (92, 32, 1, 'Bake', 'Return the pan to the three hundred fifty degree oven and bake for twenty to twenty-five minutes until the filling is set and no longer jiggles in the center when gently shaken. The edges may puff slightly and turn light golden. The center should look opaque rather than glossy.'),
  (93, 32, 2, 'Cool Completely', 'Remove from oven and let the lemon bars cool to room temperature on a wire rack, which takes about one hour. Then cover and refrigerate for at least two hours or overnight. This chilling firms up the filling and makes the bars much easier to cut into clean squares.'),
  (94, 32, 3, 'Cut and Serve', 'Just before serving, use a fine-mesh sieve to generously dust the top surface with powdered sugar. Using a sharp knife wiped clean between cuts, slice into squares or rectangles. For cleanest cuts, run the knife under hot water and dry it between each slice. Serve chilled.'),

  -- Section 33: Make Cake Layers (Recipe 12: Family Curry Powder - PRIVATE)
  (95, 33, 1, 'Mix Batter', 'In a large bowl, whisk together flour, cocoa powder, sugar, baking soda, and salt. In another bowl, beat eggs with buttermilk, oil, vanilla, and Mom''s secret ingredient. Gently fold the wet mixture into the dry ingredients just until combined, being careful not to overmix which would create a tough cake.'),
  (96, 33, 2, 'Bake', 'Divide the batter evenly between two greased and floured nine-inch round cake pans. Bake in a preheated three hundred fifty degree oven for thirty to thirty-five minutes until a toothpick inserted in the center comes out clean. Cool in pans for ten minutes, then turn out onto wire racks.'),

  -- Section 34: Frost and Assemble (Recipe 12: Family Curry Powder - PRIVATE)
  (97, 34, 1, 'Make Frosting', 'Beat one cup softened butter until creamy. Gradually add three-quarters cup cocoa powder, four cups powdered sugar, and half cup heavy cream, beating on low then increasing to high speed. Continue beating for three to four minutes until the frosting becomes light, fluffy, and incredibly smooth.'),
  (98, 34, 2, 'Assemble', 'Place one cooled cake layer on a serving plate. Spread a thick layer of frosting over the top, then place the second layer on top. Frost the sides and top generously, using an offset spatula to create smooth surfaces or decorative swirls. Refrigerate for thirty minutes to set before serving.');

SELECT setval('steps_id_seq', (SELECT MAX(id) FROM steps));
